---
- hosts: aws_ec2
  become: true
  become_user: root
  gather_facts: false
  vars:
      ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Install docker    
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: Install docker python modules
    pip: name=docker state=present executable=pip3
  - name: Install urllib3 with compatible version
    pip: name=urllib3<2.0 state=present
  - name: docker login
    docker_login: registry_url=https://index.docker.io/v1/ username=theetla password={{DOCKER_REG_PASSWORD}}
  - name: run the docker image
    docker_container: name=addbook image={{DOCKER_IMAGE}} published_ports="8080:8080"